CREATE TABLE `agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`sttProvider` varchar(64) NOT NULL,
	`sttConfig` text,
	`ttsProvider` varchar(64) NOT NULL,
	`ttsConfig` text,
	`voiceId` varchar(255),
	`llmProvider` varchar(64) NOT NULL,
	`llmModel` varchar(128),
	`llmConfig` text,
	`visionEnabled` int NOT NULL DEFAULT 0,
	`screenShareEnabled` int NOT NULL DEFAULT 0,
	`transcribeEnabled` int NOT NULL DEFAULT 0,
	`languages` text,
	`avatarModel` varchar(255),
	`systemPrompt` text,
	`mcpGatewayUrl` varchar(512),
	`mcpConfig` text,
	`langfuseEnabled` int NOT NULL DEFAULT 0,
	`langfusePublicKey` varchar(255),
	`langfuseSecretKey` varchar(255),
	`langfuseBaseUrl` varchar(512),
	`livekitUrl` varchar(512),
	`livekitApiKey` varchar(255),
	`livekitApiSecret` varchar(255),
	`deploymentStatus` enum('draft','deploying','deployed','failed','stopped') NOT NULL DEFAULT 'draft',
	`deploymentNamespace` varchar(128) DEFAULT 'agents',
	`kubernetesManifest` text,
	`widgetConfig` text,
	`widgetSnippet` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `agents` ADD CONSTRAINT `agents_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;